<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <name>jogl-zelda-triforce</name>
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.zelda</groupId>
    <artifactId>jogl-zelda-triforce</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <jogl.version>v2.4.0-rc4</jogl.version>
    </properties>
    
    <description>Choose a 3D game, create a document with an analysis of its graphical aspects. Then, choose a scene from this game to be modeled in OpenGL</description>
    
    <dependencies>

        <!-- JOGL -->
        <dependency>
            <groupId>org.jogamp.jogl</groupId>
            <artifactId>jogl-all</artifactId>
            <version>${jogl.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jogamp.jogl</groupId>
            <artifactId>jogl-all-natives-linux-aarch64</artifactId>
            <version>${jogl.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jogamp.jogl</groupId>
            <artifactId>jogl-all-natives-linux-amd64</artifactId>
            <version>${jogl.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jogamp.jogl</groupId>
            <artifactId>jogl-all-natives-linux-armv6hf</artifactId>
            <version>${jogl.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jogamp.jogl</groupId>
            <artifactId>jogl-all-natives-linux-i586</artifactId>
            <version>${jogl.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jogamp.jogl</groupId>
            <artifactId>jogl-all-natives-macosx-universal</artifactId>
            <version>${jogl.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jogamp.jogl</groupId>
            <artifactId>jogl-all-natives-windows-amd64</artifactId>
            <version>${jogl.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jogamp.jogl</groupId>
            <artifactId>jogl-all-natives-windows-i586</artifactId>
            <version>${jogl.version}</version>
        </dependency>

        <!-- GLUEGEN -->
        <dependency>
            <groupId>org.jogamp.gluegen</groupId>
            <artifactId>gluegen-rt</artifactId>
            <version>${jogl.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jogamp.gluegen</groupId>
            <artifactId>gluegen-rt-natives-macosx-universal</artifactId>
            <version>${jogl.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jogamp.gluegen</groupId>
            <artifactId>gluegen-rt-natives-linux-aarch64</artifactId>
            <version>${jogl.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jogamp.gluegen</groupId>
            <artifactId>gluegen-rt-natives-linux-amd64</artifactId>
            <version>${jogl.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jogamp.gluegen</groupId>
            <artifactId>gluegen-rt-natives-linux-armv6hf</artifactId>
            <version>${jogl.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jogamp.gluegen</groupId>
            <artifactId>gluegen-rt-natives-linux-i586</artifactId>
            <version>${jogl.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jogamp.gluegen</groupId>
            <artifactId>gluegen-rt-natives-windows-amd64</artifactId>
            <version>${jogl.version}</version>
        </dependency>

        <dependency>
            <groupId>org.jogamp.gluegen</groupId>
            <artifactId>gluegen-rt-natives-windows-i586</artifactId>
            <version>${jogl.version}</version>
        </dependency>

    </dependencies>

    <repositories>
        <repository>
            <id>jzy3d-snapshots</id>
            <name>Jzy3d Snapshots</name>
            <url>https://maven.jzy3d.org/snapshots/</url>
        </repository>
        <repository>
            <id>jzy3d-releases</id>
            <name>Jzy3d Releases</name>
            <url>https://maven.jzy3d.org/releases/</url>
        </repository>
    </repositories>

</project>